### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by bakkbone** [SadShrimpyy/SimpleFreeze#1]
`SadPermissions.getNotify()` actually returns `simplefreeze.thaw.all` instead of `simplefreeze.notify`, so anyone who can thaw is getting the notifications

**Comment by hexmont** [comment]
Hello, bakkbone.

In a certan way, you are right. The decompiled jar has a problem like that 
![image](https://github.com/user-attachments/assets/587eec5f-c2b1-4b8c-8fdd-b865c487ba13)

Honestly, when I first compiled the jar the method returned the right thing...
![image](https://github.com/user-attachments/assets/950bdc4f-50df-4862-84a6-efa73af4b9bd)

Idk, maybe the compilation have done some strange optimizaitons... Since I don't know why I didn't first committed the utils, I have done now.

You can find the updated resource on [Spigot](https://www.spigotmc.org/resources/simplefreeze-freeze-unfreeze-actions-permissions-exempt-list-name-uuid-more.108590). Enjoy :)
